### ISSUE TITLE
Issue in the code? (Cant fetch server)

### ISSUE THREAD

**Issue by qtqgyt** [ColinShark/exaroton#5]
exa.get_server("_nothing to see here_")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\exaroton\exaroton.py", line 83, in get_server
    return types.Server(**_data)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: exaroton.types.Server() argument after ** must be a mapping, not NoneType

What does this mean and how do I fix it?

**Comment by ColinShark** [comment]
> `TypeError: exaroton.types.Server() argument after ** must be a mapping, not NoneType`

That means that the data passed to the function is of NoneType (ie `None`). The function expected a mapping (indicated by the double asterisk before `_data`).

I can't see Exaroton having made any changes to their API, so my best bet is likely a wrong Server ID. Make sure to copy the ID without the hash `#`, and try again.
